### ISSUE TITLE
Authorization credentials not persisted between calls

### ISSUE THREAD

**Issue by jholleran** [paulhitz/yet-another-rest-client#47]
When opening an old request the credentials used to create the authorization token are not persisted and not displayed with the Add Credentials button is pressed.

**Comment by paulhitz** [comment]
Fixed. The username/password will now display in the modal when you re-open the modal or apply a favorite. It even works with old favorites since it works by decoding the generated value rather than persisting the credentials.

Note: This doesn't work with requests from the history tab. Auth tokens that were part of previous requests are added to the custom headers section.

@jholleran The pull request is open if you'd like to review it. #48
